//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareResourcefa_IR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResourcefa_IR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.ShareResourcefa-IR", typeof(ShareResourcefa_IR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما قفل شده است.
        /// </summary>
        public static string BlockUserMessage {
            get {
                return ResourceManager.GetString("BlockUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت موجود است.
        /// </summary>
        public static string cardNameAlreadyExist {
            get {
                return ResourceManager.GetString("cardNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا حساب کاربری خود را تایید .
        /// </summary>
        public static string ConfirmPhoneMessage {
            get {
                return ResourceManager.GetString("ConfirmPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه تصحیح پروفایل را ندارید.
        /// </summary>
        public static string EditableProfileNotAllowed {
            get {
                return ResourceManager.GetString("EditableProfileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم دسترسی.
        /// </summary>
        public static string ForniddenMessage {
            get {
                return ResourceManager.GetString("ForniddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا به این سرویس درخواست داده اید.
        /// </summary>
        public static string HasReserveRequest {
            get {
                return ResourceManager.GetString("HasReserveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد صحیح نمیباشد.
        /// </summary>
        public static string InCorrectPassword {
            get {
                return ResourceManager.GetString("InCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است.
        /// </summary>
        public static string InternalServerMessage {
            get {
                return ResourceManager.GetString("InternalServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ورودی بیشتر از موجودی کیف پول شما میباشد.
        /// </summary>
        public static string InvaliAmountForTransaction {
            get {
                return ResourceManager.GetString("InvaliAmountForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواب نامعتبر است.
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس نامعتبر است.
        /// </summary>
        public static string InvalidaServiceCategory {
            get {
                return ResourceManager.GetString("InvalidaServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش نامعتبر.
        /// </summary>
        public static string InvalidAttamp {
            get {
                return ResourceManager.GetString("InvalidAttamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف نامعتبر است.
        /// </summary>
        public static string InvalidDiscointCode {
            get {
                return ResourceManager.GetString("InvalidDiscointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی نامعتبر است.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعتبر.
        /// </summary>
        public static string InvalidPackageType {
            get {
                return ResourceManager.GetString("InvalidPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل صحیح نمیباشد.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال نامعتبر است.
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سرویس نامعتبر است.
        /// </summary>
        public static string InValidServiceType {
            get {
                return ResourceManager.GetString("InValidServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری قفل شده است.
        /// </summary>
        public static string LockedOutMessage {
            get {
                return ResourceManager.GetString("LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالی موجود نیست.
        /// </summary>
        public static string Noquestoin {
            get {
                return ResourceManager.GetString("Noquestoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول شما کافی نمیباشد.
        /// </summary>
        public static string NotEnoughtBalance {
            get {
                return ResourceManager.GetString("NotEnoughtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه ایی یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد پیام مجاز شما به پایان رسید.
        /// </summary>
        public static string NumberOfFreeMessagesCompleted {
            get {
                return ResourceManager.GetString("NumberOfFreeMessagesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل  تکراریست.
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در آپلود فایل رخ داده است.
        /// </summary>
        public static string problemUploadingTheFileMessage {
            get {
                return ResourceManager.GetString("problemUploadingTheFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل شما برای این سرویس رد شده.
        /// </summary>
        public static string ProfileRejectedMessage {
            get {
                return ResourceManager.GetString("ProfileRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس دهنده در دسترس نمیباشد.
        /// </summary>
        public static string ProviderIsUnAvailableMessage {
            get {
                return ResourceManager.GetString("ProviderIsUnAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست توسط سرویس دهنده تایید نشده است.
        /// </summary>
        public static string RequestNotConfirmedMessgaes {
            get {
                return ResourceManager.GetString("RequestNotConfirmedMessgaes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این سرویس توسط ادمین غیر فعال گردید.
        /// </summary>
        public static string ServiceIsDisabled {
            get {
                return ResourceManager.GetString("ServiceIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس یافت نشد.
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی رخ داده.
        /// </summary>
        public static string somethingWentWrongForChaing {
            get {
                return ResourceManager.GetString("somethingWentWrongForChaing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت موفقیت آمیز.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام الزامیست.
        /// </summary>
        public static string TextIsRequired {
            get {
                return ResourceManager.GetString("TextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل نامعتبر است.
        /// </summary>
        public static string TheFileIsInValid {
            get {
                return ResourceManager.GetString("TheFileIsInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل الزامیست.
        /// </summary>
        public static string TheFileIsRequired {
            get {
                return ResourceManager.GetString("TheFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل زیاد است.
        /// </summary>
        public static string TheFileIsTooLarge {
            get {
                return ResourceManager.GetString("TheFileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت بسته شده است.
        /// </summary>
        public static string TicketIsClosedMessage {
            get {
                return ResourceManager.GetString("TicketIsClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم دسترسی.
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور یا  شماره موبایل صحیح نمی باشد.
        /// </summary>
        public static string UnMathPhoneNumberPassword {
            get {
                return ResourceManager.GetString("UnMathPhoneNumberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وویس الزامیست.
        /// </summary>
        public static string VoiceIsrequired {
            get {
                return ResourceManager.GetString("VoiceIsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم وویس زیاد است.
        /// </summary>
        public static string VoiceIsTooLarge {
            get {
                return ResourceManager.GetString("VoiceIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما سرویس دهنده هستیدونمیتوانید بسته بخرید.
        /// </summary>
        public static string YouAreProviderOfThisService {
            get {
                return ResourceManager.GetString("YouAreProviderOfThisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نمیتوانید به حساب شرکتی درخواست دهید.
        /// </summary>
        public static string YouCantRequestToACompay {
            get {
                return ResourceManager.GetString("YouCantRequestToACompay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست نامعتبر.
        /// </summary>
        public static string YouCantRequestToYourSelf {
            get {
                return ResourceManager.GetString("YouCantRequestToYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما درحال حاضر بسته فعال دارید.
        /// </summary>
        public static string YouCurrentlyHaveAnActivePackage {
            get {
                return ResourceManager.GetString("YouCurrentlyHaveAnActivePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول شما کافی نیست.
        /// </summary>
        public static string YouDOntAnyWallet {
            get {
                return ResourceManager.GetString("YouDOntAnyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما پلن فعالی ندارید.
        /// </summary>
        public static string YouDontHaveAnyPackage {
            get {
                return ResourceManager.GetString("YouDontHaveAnyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما پلن فعالی ندارید یا زمان پلن به پایان رسید.
        /// </summary>
        public static string YoudontHavePlanOrPlanIsExpired {
            get {
                return ResourceManager.GetString("YoudontHavePlanOrPlanIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا در این دسته بندی عضو شرکت بوده اید.
        /// </summary>
        public static string YouHaveReservedService {
            get {
                return ResourceManager.GetString("YouHaveReservedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته شمابه پایان رسیده.
        /// </summary>
        public static string YourPackageExpired {
            get {
                return ResourceManager.GetString("YourPackageExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما بسته فعالی ندارید یا بسته شما منقصی شده.
        /// </summary>
        public static string YourPackageExpiredOrNoPlan {
            get {
                return ResourceManager.GetString("YourPackageExpiredOrNoPlan", resourceCulture);
            }
        }
    }
}
