//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShareResourceen_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResourceen_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.ShareResourceen-US", typeof(ShareResourceen_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked by admin.
        /// </summary>
        public static string BlockUserMessage {
            get {
                return ResourceManager.GetString("BlockUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card name already exist.
        /// </summary>
        public static string cardNameAlreadyExist {
            get {
                return ResourceManager.GetString("cardNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm Your Account.
        /// </summary>
        public static string ConfirmPhoneMessage {
            get {
                return ResourceManager.GetString("ConfirmPhoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit profiles.
        /// </summary>
        public static string EditableProfileNotAllowed {
            get {
                return ResourceManager.GetString("EditableProfileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acess Denied.
        /// </summary>
        public static string ForniddenMessage {
            get {
                return ResourceManager.GetString("ForniddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a registered request to this service.
        /// </summary>
        public static string HasReserveRequest {
            get {
                return ResourceManager.GetString("HasReserveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inCorrect password.
        /// </summary>
        public static string InCorrectPassword {
            get {
                return ResourceManager.GetString("InCorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sth went wrong.
        /// </summary>
        public static string InternalServerMessage {
            get {
                return ResourceManager.GetString("InternalServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the entry amount is more than your wallet balance.
        /// </summary>
        public static string InvaliAmountForTransaction {
            get {
                return ResourceManager.GetString("InvaliAmountForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid answer .
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid service category.
        /// </summary>
        public static string InvalidaServiceCategory {
            get {
                return ResourceManager.GetString("InvalidaServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid attamp.
        /// </summary>
        public static string InvalidAttamp {
            get {
                return ResourceManager.GetString("InvalidAttamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid discount code.
        /// </summary>
        public static string InvalidDiscointCode {
            get {
                return ResourceManager.GetString("InvalidDiscointCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid package type.
        /// </summary>
        public static string InvalidPackageType {
            get {
                return ResourceManager.GetString("InvalidPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid question.
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service type is invalid.
        /// </summary>
        public static string InValidServiceType {
            get {
                return ResourceManager.GetString("InValidServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user account locked out.
        /// </summary>
        public static string LockedOutMessage {
            get {
                return ResourceManager.GetString("LockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no question.
        /// </summary>
        public static string Noquestoin {
            get {
                return ResourceManager.GetString("Noquestoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your wallet balance is not enough.
        /// </summary>
        public static string NotEnoughtBalance {
            get {
                return ResourceManager.GetString("NotEnoughtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authorized message count has expired.
        /// </summary>
        public static string NumberOfFreeMessagesCompleted {
            get {
                return ResourceManager.GetString("NumberOfFreeMessagesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number  already  exist.
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is a problem to uploading the file.
        /// </summary>
        public static string problemUploadingTheFileMessage {
            get {
                return ResourceManager.GetString("problemUploadingTheFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your profile rejected for this service.
        /// </summary>
        public static string ProfileRejectedMessage {
            get {
                return ResourceManager.GetString("ProfileRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provide is not available.
        /// </summary>
        public static string ProviderIsUnAvailableMessage {
            get {
                return ResourceManager.GetString("ProviderIsUnAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request not confirmed by provider messgaes.
        /// </summary>
        public static string RequestNotConfirmedMessgaes {
            get {
                return ResourceManager.GetString("RequestNotConfirmedMessgaes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service is disable.
        /// </summary>
        public static string ServiceIsDisabled {
            get {
                return ResourceManager.GetString("ServiceIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service notfound.
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went wrong .
        /// </summary>
        public static string somethingWentWrongForChaing {
            get {
                return ResourceManager.GetString("somethingWentWrongForChaing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful Submit.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text Is required.
        /// </summary>
        public static string TextIsRequired {
            get {
                return ResourceManager.GetString("TextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file format is invalid.
        /// </summary>
        public static string TheFileIsInValid {
            get {
                return ResourceManager.GetString("TheFileIsInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file is required.
        /// </summary>
        public static string TheFileIsRequired {
            get {
                return ResourceManager.GetString("TheFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file is too large.
        /// </summary>
        public static string TheFileIsTooLarge {
            get {
                return ResourceManager.GetString("TheFileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the tiket isclosed.
        /// </summary>
        public static string TicketIsClosedMessage {
            get {
                return ResourceManager.GetString("TicketIsClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are  unauthorized.
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid phone number or password.
        /// </summary>
        public static string UnMathPhoneNumberPassword {
            get {
                return ResourceManager.GetString("UnMathPhoneNumberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voice is required.
        /// </summary>
        public static string VoiceIsrequired {
            get {
                return ResourceManager.GetString("VoiceIsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vocie is too large.
        /// </summary>
        public static string VoiceIsTooLarge {
            get {
                return ResourceManager.GetString("VoiceIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are provider of service . you cant buy package.
        /// </summary>
        public static string YouAreProviderOfThisService {
            get {
                return ResourceManager.GetString("YouAreProviderOfThisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cant request to a compay because you are a company.
        /// </summary>
        public static string YouCantRequestToACompay {
            get {
                return ResourceManager.GetString("YouCantRequestToACompay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid request.
        /// </summary>
        public static string YouCantRequestToYourSelf {
            get {
                return ResourceManager.GetString("YouCantRequestToYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you currently have an active package.
        /// </summary>
        public static string YouCurrentlyHaveAnActivePackage {
            get {
                return ResourceManager.GetString("YouCurrentlyHaveAnActivePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have wallet.
        /// </summary>
        public static string YouDOntAnyWallet {
            get {
                return ResourceManager.GetString("YouDOntAnyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you dont have any  active package.
        /// </summary>
        public static string YouDontHaveAnyPackage {
            get {
                return ResourceManager.GetString("YouDontHaveAnyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already been a member of this category.
        /// </summary>
        public static string YouHaveReservedService {
            get {
                return ResourceManager.GetString("YouHaveReservedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your package is expired.
        /// </summary>
        public static string YourPackageExpired {
            get {
                return ResourceManager.GetString("YourPackageExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your dont have package or package is expire.
        /// </summary>
        public static string YourPackageExpiredOrNoPlan {
            get {
                return ResourceManager.GetString("YourPackageExpiredOrNoPlan", resourceCulture);
            }
        }
    }
}
